apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: service_will_share_ip
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
    - port: 22
      name: ssh
      targetPort: 22

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Never
          image: nginx-custom
          env:
            - name: INFLUX_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: influxdb-secret
            - name: INFLUX_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: influxdb-secret
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
            httpGet:
              path: /
              scheme: HTTPS
              port: 443
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 22
              name: ftps
