apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: service_will_share_ip
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      name: https
      protocol: TCP
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          env:
            - name: PMA_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: pma-secret
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: pma-secret
            - name: INFLUX_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: influxdb-secret
            - name: INFLUX_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: influxdb-secret
          livenessProbe:
            initialDelaySeconds: 40
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
            httpGet:
              path: /
              scheme: HTTPS
              port: 5000
          readinessProbe:
            initialDelaySeconds: 40
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
            httpGet:
              path: /
              port: 5000
              scheme: HTTPS
          image: phpmyadmin-custom
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
