apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
type: kubernetes.io/basic-auth
stringData:
  username: wp-secret-user
  password: wp-secret-password
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: edebi_secure_password
---
apiVersion: v1
kind: Secret
metadata:
  name: pma-secret
type: kubernetes.io/basic-auth
stringData:
  username: pma-secret-user
  password: pma-secret-password
---
apiVersion: v1
kind: Secret
metadata:
  name: ftps-secret
type: kubernetes.io/basic-auth
stringData:
  username: ftps-user
  password: ftps-secret-password
---
apiVersion: v1
kind: Secret
metadata:
  name: wp-admin-secret
type: kubernetes.io/basic-auth
stringData:
  username: wp-admin-user
  password: wp-admin-password
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: influxpassword